---

- name: Create gateway-logs index pattern within {{ item.name }} space
  uri:
    url: "{{ kibana_url }}/s/{{ item.name }}/api/saved_objects/index-pattern/gateway-logs-*?overwrite=true"
    method: POST
    body: "{{ lookup('template', 'roles/kibana/templates/gateway_logs_index_pattern.json.j2') }}"
    status_code: 200
    body_format: json
    headers:
      Content-Type: application/json
      kbn-xsrf: true
  with_items:
    "{{ environments}}"
  when:
    item.name in existing_spaces
