---

- name: Set index-lifecycle-management policies for environments
  uri:
    url: "{{ elasticsearch_api_url }}/_ilm/policy/{{ item.name }}-logging-policy"
    method: PUT
    body: "{{ lookup('template', 'roles/index-lifecycle-management/templates/environment_ilm_policy.json.j2') }}"
    status_code: 200
    body_format: json
    headers:
      Content-Type: application/json
      kbn-xsrf: true
  with_items:
    "{{ environments }}"
